version: "3.9"
services:
  my-server:
    build: ./part5
    container_name: my-server
    tty: true
  nginxer:
    build: ./part6
    container_name: nginxer
    ports:
      - 8000:8080
    tty: true
    volumes:
      - ./part6/nginx.conf:/etc/nginx/nginx.conf
